import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { NavBar } from "./NavBar";
import { ConfigProvider, theme } from "antd";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ConfigProvider theme={{
        algorithm: theme.defaultAlgorithm,
        token: {
            colorPrimary: '#00b96b',
            colorPrimaryHover: '#00b96b',
            colorPrimaryActive: '#00b96b',
            colorPrimaryBorder: '#00b96b',
            colorPrimaryBorderHover: '#00b96b',
            colorPrimaryBg: '#00b96b',
        }
      }}>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <NavBar />
          <main>
          {children}

          </main>
        </body>

      </ConfigProvider>

      
    </html>
  );
}
